# Generated by Django 5.0.3 on 2024-03-19 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_customuser_email_alter_customuser_regno_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_category', models.CharField(max_length=20)),
                ('book_name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=100)),
                ('number_of_books', models.IntegerField()),
                ('book_type', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
