# Generated by Django 5.0.3 on 2024-03-27 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_borrowing_is_borrowed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowing',
            name='is_borrowed',
            field=models.BooleanField(default=True),
        ),
    ]
