# Generated by Django 5.0.3 on 2024-03-29 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_alter_book_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowing',
            name='due_fine',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
