# Generated by Django 5.0.3 on 2024-03-29 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_borrowing_due_fine'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borrowing',
            name='due_fine',
        ),
    ]
