# Generated by Django 5.0.3 on 2024-04-03 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_order_entry_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='entry_id',
        ),
    ]
