# Generated by Django 5.0.3 on 2024-04-07 08:41

import embed_video.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_invoice'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_name', models.CharField(max_length=40)),
                ('category', models.CharField(max_length=20)),
                ('video', embed_video.fields.EmbedVideoField()),
            ],
        ),
    ]
